name: Flatpak CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flatpak
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder

      - name: Add Flathub remote
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build Flatpak
        run: |
          flatpak-builder build-dir flatpak/io.github.rajnisht7.ClipVault.yml \
            --install-deps-from=flathub \
            --repo=repo \
            --force-clean
